version: '3.8'

services:
  taskmanager:
    build: .
    container_name: taskmanager
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      # База данных
      - ./department/database:/app/department/database
      # RAG хранилище
      - ./department/rag/vector_db:/app/department/rag/vector_db
    environment:
      - PYTHONUNBUFFERED=1
    # Доступ к хосту для LM Studio (localhost:1234)
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
